version: '3.3'
services:
  mongo:
    image: bitnami/mongodb:5.0.9
    restart: always
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: example
      MONGODB_DATABASE: ticketbot
      MONGODB_USERNAME: ticketbot
      MONGODB_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo:/bitnami/mongodb

  bot:
    image: ghcr.io/thenilsdev/discord-ticket-support:2
    restart: always
    environment:
      - DEBUG=false
      - SENTRY_ENABLED=false
      - SENTRY_DSN=
      - DISCORD_TOKEN=token
      - DISCORD_SHARDS_TOTAL=1
      - DISCORD_SHARDS_MIN=0
      - DISCORD_SHARDS_MAX=0
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=ticketbot
      - MONGODB_USERNAME=ticketbot
      - MONGODB_PASSWORD=password
    volumes:
      - bot-logs:/logs

volumes:
  mongo: { }
  bot-logs: { }
